image: trion/ng-cli

cache:
    paths:
        - node_modules/
        - functions/node_modules/

before_script:
    - npm i -g firebase-tools

stages:
    - install
    - build
    - deploy

# Install dependencies
install:
    stage: install
    script:
        - echo "Installing dependencies for Production..."
        - yarn install --immutable --immutable-cache --check-cache
    only:
        refs:
            - master
            - develop

# Build - Production
build:prod:
    stage: build
    script:
        - echo "Building for Production..."
        - ng build --configuration=production
    only:
        refs:
            - master
        # changes:
            # - src/**/*

# Build - Develop
build:dev:
    stage: build
    script:
        - echo "Building for Staging..."
        - ng build --configuration=staging
    only:
        refs:
            - develop
        # changes:
            # - src/**/*

# Deploy - Production
deploy:prod:
    stage: deploy
    script:
        - echo "Building for Production..."
        - yarn firebase deploy --token $FIREBASE_TOKEN --only hosting -P prod
    variables:
        FIREBASE_TOKEN: $FIREBASE_TOKEN
    only:
        refs:
            - master
        # changes:
            # - src/**/*

# Deploy - Develop
deploy:dev:
    stage: deploy
    script:
        - echo "Building for Staging..."
        - yarn firebase deploy --token $FIREBASE_TOKEN --only hosting -P dev
    variables:
        FIREBASE_TOKEN: $FIREBASE_TOKEN
    only:
        refs:
            - develop
        # changes:
            # - src/**/*
